import json,urllib.request,urllib.error,uuid,base64
API=__import__('os').environ.get('API_URL','https://vagasio-api-staging.onrender.com');u=uuid.uuid4().hex[:8]
def req(method,path,b=None,t=None):
 d=json.dumps(b).encode() if b is not None else None;h={'Content-Type':'application/json'}
 if t:h['Authorization']='Bearer '+t
 try:
  r=urllib.request.urlopen(urllib.request.Request(API+path,data=d,headers=h,method=method),timeout=50);return r.status,json.loads(r.read() or b'{}')
 except urllib.error.HTTPError as e:
  try:return e.code,json.loads(e.read() or b'{}')
  except:return e.code,{}
def post(p,b,t=None):return req('POST',p,b,t)
e=post('/api/empresa/cadastro',{'empresa_nome':'F5 Talent '+u,'admin_nome':'Admin','admin_email':'f5a'+u+'@example.test','email_principal':'f5a'+u+'@example.test','admin_senha':'Teste12345!'});te=e[1]['token'];v=post('/api/empresa/vagas',{'titulo':'F5 Talent '+u,'cidade':'SP','estado':'SP','area':'Tecnologia','etapas':[{'nome':'I'}]},te);vid=v[1]['vaga']['id'];c=post('/api/candidato/cadastro',{'nome':'Talent '+u,'email':'f5c'+u+'@example.test','senha':'Teste12345!','cidade':'SP','banco_talentos':True,'recebe_comunicacoes':True});tc=c[1]['token'];cid=c[1]['candidato']['id']
# Candidate has not applied; it must still appear in talent search and be eligible for an explicit invitation.
matches=req('GET',f'/api/empresa/vagas/{vid}/matches',t=te);invite=post(f'/api/empresa/candidatos/{cid}/convite',{'vaga_id':vid,'mensagem':'Convite de teste'},te);duplicate=post(f'/api/empresa/candidatos/{cid}/convite',{'vaga_id':vid},te);cancel=req('DELETE',f'/api/empresa/candidatos/{cid}/convite?vaga_id={vid}',t=te);reinvite=post(f'/api/empresa/candidatos/{cid}/convite',{'vaga_id':vid},te);before_apply=req('GET',f'/api/empresa/vagas/{vid}/matches',t=te)[1].get('matches',[]);apply=post(f'/api/candidato/candidatar/{vid}',{},tc);after_apply=req('GET',f'/api/empresa/vagas/{vid}/matches',t=te)[1].get('matches',[]);search=req('GET','/api/empresa/candidatos?limite=100',t=te);triage=req('GET',f'/api/empresa/vagas/{vid}/ia/triagem',t=te);cross=req('GET','/api/empresa/vagas/999999999/matches',t=te);no_consent=post('/api/candidato/cadastro',{'nome':'NoConsent '+u,'email':'f5n'+u+'@example.test','senha':'Teste12345!','banco_talentos':False,'recebe_comunicacoes':False});nid=no_consent[1]['candidato']['id'];invite_no=post(f'/api/empresa/candidatos/{nid}/convite',{'vaga_id':vid},te)
print(json.dumps({'matches_status':matches[0],'match_ids':[x.get('candidato_id') for x in matches[1].get('matches',[])],'search_status':search[0],'search_ids':[x.get('id') for x in search[1].get('candidatos',[])],'triage_status':triage[0],'triage_top_id':(triage[1].get('ranking') or [{}])[0].get('candidato_id'),'cross_tenant_status':cross[0],'talent_candidate_id':cid,'invite_status':invite[0],'duplicate_invite_status':duplicate[0],'cancel_status':cancel[0],'reinvite_status':reinvite[0],'email_enviado':invite[1].get('email_enviado'),'before_apply_candidatura_id':before_apply[0].get('candidatura_id') if before_apply else None,'apply_status':apply[0],'after_apply_candidatura_id':after_apply[0].get('candidatura_id') if after_apply else None,'nonconsent_invite_status':invite_no[0]},ensure_ascii=False))
