const webpush = require('web-push');
const { pool } = require('./db');
let ready = false;
function initPush() { if (ready) return true; if (!process.env.VAPID_PUBLIC_KEY || !process.env.VAPID_PRIVATE_KEY) return false; webpush.setVapidDetails(process.env.VAPID_SUBJECT || 'mailto:admin@localhost.invalid', process.env.VAPID_PUBLIC_KEY, process.env.VAPID_PRIVATE_KEY); ready = true; return true; }
function valid(s) { return s && typeof s.endpoint === 'string' && s.endpoint.length <= 2048 && s.keys && typeof s.keys.p256dh === 'string' && typeof s.keys.auth === 'string'; }
async function save(candidatoId, s, dispositivo) { if (!valid(s)) throw new Error('Assinatura push inválida'); const r=await pool.query(`INSERT INTO push_subscriptions (candidato_id,endpoint,p256dh,auth,dispositivo,ativo,atualizado_em,ultimo_uso_em) VALUES ($1,$2,$3,$4,$5,TRUE,NOW(),NOW()) ON CONFLICT(endpoint) DO UPDATE SET candidato_id=EXCLUDED.candidato_id,p256dh=EXCLUDED.p256dh,auth=EXCLUDED.auth,dispositivo=EXCLUDED.dispositivo,ativo=TRUE,atualizado_em=NOW(),ultimo_uso_em=NOW() RETURNING id`,[candidatoId,s.endpoint,s.keys.p256dh,s.keys.auth,dispositivo||null]); return r.rows[0]; }
async function remove(candidatoId, endpoint) { await pool.query('UPDATE push_subscriptions SET ativo=FALSE,atualizado_em=NOW() WHERE candidato_id=$1 AND endpoint=$2',[candidatoId,endpoint]); }
async function send(candidatoId, payload) { if (!initPush()) return {ok:false,reason:'vapid_not_configured'}; const r=await pool.query('SELECT id,endpoint,p256dh,auth FROM push_subscriptions WHERE candidato_id=$1 AND ativo=TRUE',[candidatoId]); let sent=0; for(const row of r.rows){try{await webpush.sendNotification({endpoint:row.endpoint,keys:{p256dh:row.p256dh,auth:row.auth}},JSON.stringify(payload)); sent++; await pool.query('UPDATE push_subscriptions SET ultimo_uso_em=NOW() WHERE id=$1',[row.id]);}catch(e){if(e.statusCode===404||e.statusCode===410)await pool.query('UPDATE push_subscriptions SET ativo=FALSE,atualizado_em=NOW() WHERE id=$1',[row.id]);}} return {ok:true,sent}; }
module.exports={initPush,save,remove,send};
